# generate school
School.create!(name: 'โรงเรียนจุฬาภรณราชวิทยาลัย ปทุมธานี')
School.create!(name: 'โรงเรียนคณะราษฎร์บำรุงปทุมธานี')
School.create!(name: 'โรงเรียนธัญบุรี')
School.create!(name: 'โรงเรียนสายปัญญารังสิต')
School.create!(name: 'โรงเรียนปทุมวิไล')
School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย รังสิต')
School.create!(name: 'โรงเรียนทีปังกรวิทยาพัฒน์ (มัธยมวัดหัตถสารเกษตร) ในพระราชูปถัมภ์')
School.create!(name: 'โรงเรียนมัธยมสังคีตวิทยา กรุงเทพมหานคร')
School.create!(name: 'โรงเรียนประถมศึกษาธรรมศาสตร์')
School.create!(name: 'โรงเรียนสาธิตแห่งมหาวิทยาลัยรังสิต')
School.create!(name: 'โรงเรียนสาธิตมหาวิทยาลัยราชภัฏวไลยอลงกรณ์ ในพระบรมราชูปถัมภ์')
School.create!(name: 'โรงเรียนโชคชัยรังสิต')
School.create!(name: 'โรงเรียนเซนต์โยเซฟเมืองเอก')
School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
School.create!(name: 'โรงเรียนธัญวิทย์')
School.create!(name: 'โรงเรียนบรรจบรักษ์')
School.create!(name: 'โรงเรียนบริบูรณ์ศิลป์รังสิต')
School.create!(name: 'โรงเรียนบ้านพลอย')
School.create!(name: 'โรงเรียนเฟื่องฟ้าวิทยา')
School.create!(name: 'โรงเรียนบีคอนเฮาส์แย้มสอาดรังสิต')
School.create!(name: 'โรงเรียนรังสฤษฎิ์สองภาษา')
School.create!(name: 'โรงเรียนรังสิตวิทยา')
School.create!(name: 'โรงเรียนรัตนโกสินทร์-รังสิต')
School.create!(name: 'โรงเรียนวนิษา')
School.create!(name: 'โรงเรียนศรีจิตรา')
School.create!(name: 'โรงเรียนสารสาสน์วิเทศคลองหลวง')
School.create!(name: 'โรงเรียนสารสาสน์วิเทศรังสิต')
School.create!(name: 'โรงเรียนวัฒนาวิทยาลัย')
School.create!(name: 'โรงเรียนสามเสนวิทยาลัย')
School.create!(name: 'โรงเรียนหอวัง')
School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย นนทบุรี')
School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย')
School.create!(name: 'โรงเรียนสารสาสน์วิเทศราชพฤกษ์')
School.create!(name: 'โรงเรียนเซนต์ฟรังซีสเซเวียร์')
School.create!(name: 'โรงเรียนพิชญศึกษา')
School.create!(name: 'โรงเรียนพระหฤทัยนนทบุรี')
School.create!(name: 'โรงเรียนเซนต์คาเบรียล')
School.create!(name: 'โรงเรียนไผทอุดมศึกษา')
School.create!(name: 'โรงเรียนอัมพรไพศาล')
School.create!(name: 'โรงเรียนจุฑารัตน์วิทยา')
School.create!(name: 'โรงเรียนไตรราชวิทยา')
School.create!(name: 'โรงเรียนอมาตยกุล')
School.create!(name: 'โรงเรียนจิตรลดา')
School.create!(name: 'โรงเรียนราชินีบน')
School.create!(name: 'โรงเรียนนวมินทราชินูทิศ หอวัง นนทบุรี')
School.create!(name: 'โรงเรียนสาธิตแห่งมหาวิทยาลัยเกษตรศาสตร์')
School.create!(name: 'โรงเรียนยอแซฟอยุธยา')
School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย')
School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย ประถม')
School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย 2')
