# generate school
# School.create!(name: 'โรงเรียนจุฬาภรณราชวิทยาลัย ปทุมธานี')
# School.create!(name: 'โรงเรียนคณะราษฎร์บำรุงปทุมธานี')
# School.create!(name: 'โรงเรียนธัญบุรี')
# School.create!(name: 'โรงเรียนสายปัญญารังสิต')
# School.create!(name: 'โรงเรียนปทุมวิไล')
# School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย รังสิต')
# School.create!(name: 'โรงเรียนทีปังกรวิทยาพัฒน์ (มัธยมวัดหัตถสารเกษตร) ในพระราชูปถัมภ์')
# School.create!(name: 'โรงเรียนมัธยมสังคีตวิทยา กรุงเทพมหานคร')
# School.create!(name: 'โรงเรียนประถมศึกษาธรรมศาสตร์')
# School.create!(name: 'โรงเรียนสาธิตแห่งมหาวิทยาลัยรังสิต')
# School.create!(name: 'โรงเรียนสาธิตมหาวิทยาลัยราชภัฏวไลยอลงกรณ์ ในพระบรมราชูปถัมภ์')
# School.create!(name: 'โรงเรียนโชคชัยรังสิต')
# School.create!(name: 'โรงเรียนเซนต์โยเซฟเมืองเอก')
# School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
# School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
# School.create!(name: 'โรงเรียนทิพพากรวิทยาการ')
# School.create!(name: 'โรงเรียนธัญวิทย์')
# School.create!(name: 'โรงเรียนบรรจบรักษ์')
# School.create!(name: 'โรงเรียนบริบูรณ์ศิลป์รังสิต')
# School.create!(name: 'โรงเรียนบ้านพลอย')
# School.create!(name: 'โรงเรียนเฟื่องฟ้าวิทยา')
# School.create!(name: 'โรงเรียนบีคอนเฮาส์แย้มสอาดรังสิต')
# School.create!(name: 'โรงเรียนรังสฤษฎิ์สองภาษา')
# School.create!(name: 'โรงเรียนรังสิตวิทยา')
# School.create!(name: 'โรงเรียนรัตนโกสินทร์-รังสิต')
# School.create!(name: 'โรงเรียนวนิษา')
# School.create!(name: 'โรงเรียนศรีจิตรา')
# School.create!(name: 'โรงเรียนสารสาสน์วิเทศคลองหลวง')
# School.create!(name: 'โรงเรียนสารสาสน์วิเทศรังสิต')
# School.create!(name: 'โรงเรียนวัฒนาวิทยาลัย')
# School.create!(name: 'โรงเรียนสามเสนวิทยาลัย')
# School.create!(name: 'โรงเรียนหอวัง')
# School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย นนทบุรี')
# School.create!(name: 'โรงเรียนสวนกุหลาบวิทยาลัย')
# School.create!(name: 'โรงเรียนสารสาสน์วิเทศราชพฤกษ์')
# School.create!(name: 'โรงเรียนเซนต์ฟรังซีสเซเวียร์')
# School.create!(name: 'โรงเรียนพิชญศึกษา')
# School.create!(name: 'โรงเรียนพระหฤทัยนนทบุรี')
# School.create!(name: 'โรงเรียนเซนต์คาเบรียล')
# School.create!(name: 'โรงเรียนไผทอุดมศึกษา')
# School.create!(name: 'โรงเรียนอัมพรไพศาล')
# School.create!(name: 'โรงเรียนจุฑารัตน์วิทยา')
# School.create!(name: 'โรงเรียนไตรราชวิทยา')
# School.create!(name: 'โรงเรียนอมาตยกุล')
# School.create!(name: 'โรงเรียนจิตรลดา')
# School.create!(name: 'โรงเรียนราชินีบน')
# School.create!(name: 'โรงเรียนนวมินทราชินูทิศ หอวัง นนทบุรี')
# School.create!(name: 'โรงเรียนสาธิตแห่งมหาวิทยาลัยเกษตรศาสตร์')
# School.create!(name: 'โรงเรียนยอแซฟอยุธยา')
# School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย')
# School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย ประถม')
# School.create!(name: 'โรงเรียนฤทธิยะวรรณาลัย 2')
# School.create!(name: 'โรงเรียนชุมชนวัดบางขัน')
# School.create!(name: 'โรงเรียนดอนเมืองทหารอากาศบำรุง')
# School.create!(name: 'โรงเรียนพิทยรังสี')
# School.create!(name: 'โรงเรียนธรรมศาสตร์คลองหลวงวิทยาคม')
# School.create!(name: 'โรงเรียนเปรมฤทัย')
# School.create!(name: 'โรงเรียนผ่องสุวรรณวิทยา')
# School.create!(name: 'โรงเรียนมาลาสวรรค์พิทยา')
# School.create!(name: 'โรงเรียนวัดดอนเมือง(ทหารอากาศอุทิศ)')
# School.create!(name: 'โรงเรียนวัดป่างิ้ว')
# School.create!(name: 'โรงเรียนวัดเปรมประชากร')
# School.create!(name: 'โรงเรียนวัดหงส์ปทุมาวาส')
# School.create!(name: 'โรงเรียนสตรีวรนาถบางเขน')
# School.create!(name: 'โรงเรียนสารสาสน์วิเทศบางบัวทอง')
# School.create!(name: 'โรงเรียนสารสาสน์วิเทศคลองหลวง')
# School.create!(name: 'โรงเรียนหอวัง ปทุมธานี')
# School.create!(name: 'โรงเรียนอนุบาลปทุมธานี')
# School.create!(name: 'โรงเรียนอนุบาลพระนครศรีอยุธยา')
# School.create!(name: 'โรงเรียนอนุบาลวัดอ่างทอง')
# School.create!(name: 'โรงเรียนอนุบาลสามเสนฯ')
# School.create!(name: 'โรงเรียนอรรถมิตร')
# School.create!(name: 'โรงเรียนอุดมวิทยา')
School.create!(name: 'โรงเรียนชุมชนประชาธิปัตย์วิทยาคาร')
School.create!(name: 'โรงเรียนบึงเขาย้อน')
School.create!(name: 'โรงเรียนเทศบาลท่าโขลง')
School.create!(name: 'โรงเรียนวิภารัตน์')
School.create!(name: 'โรงเรียนผดุงศิษย์พิทยา')
School.create!(name: 'โรงเรียนทรงวิทย์ศึกษา')
School.create!(name: 'โรงเรียนสารวิทยา')
School.create!(name: 'โรงเรียนสาธิต มศว องครักษ์')
School.create!(name: 'โรงเรียนพลอาสา')
School.create!(name: 'โรงเรียนเฉลิมพระเกียรติรังสิต คลอง4')
School.create!(name: 'โรงเรียนเทพศิรินทร์')
School.create!(name: 'โรงเรียนสายปัญญา')
School.create!(name: 'โรงเรียนสารสาสน์วิเทศสายไหม')
School.create!(name: 'โรงเรียนเซนต์โยเซฟคอนแวนต์')
